# Generated by Django 4.2.9 on 2024-01-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=100, null=True)),
                ('payment', models.DateTimeField(auto_now=True)),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
