# Generated by Django 4.2.9 on 2024-01-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment',
            new_name='date_time',
        ),
    ]
