# Generated by Django 5.0.1 on 2024-02-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
