# Generated by Django 5.0.1 on 2024-02-21 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 16, 9, 34, 809886)),
        ),
    ]
