# Generated by Django 5.0.1 on 2024-02-21 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 23, 12, 21, 185819)),
        ),
    ]
