# Generated by Django 5.0.1 on 2024-02-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin'), ('cook', 'Cook'), ('cashier', 'Cashier')], max_length=20),
        ),
    ]
