# Generated by Django 4.2.9 on 2024-01-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
