# Generated by Django 5.0.1 on 2024-02-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='is_cancelled',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
