# Generated by Django 5.0.1 on 2024-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderline_is_cancelled_alter_orderline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
