# Generated by Django 5.0.1 on 2024-02-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderline_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='date_time',
        ),
    ]
