# Generated by Django 5.0.1 on 2024-02-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_orderline_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
