# Generated by Django 5.0.1 on 2024-02-10 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 21, 52, 6, 809715)),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='orderline_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 21, 52, 6, 809921)),
        ),
    ]
