# Generated by Django 5.0.1 on 2024-02-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_item_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
