# Generated by Django 5.0.1 on 2024-02-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
